M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date Вт 26 сен 2023 13:38:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-26T13:38:57+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X59.975Y-33.661
X65.755Y-33.661
T2
X32.745Y-37.595
X32.745Y-45.595
T0
M30
